version: "3.6"
services:
  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    restart: always

  hasura-postgres:
    image: postgres:${HASURA_POSTGRES_VERSION:-latest}
    restart: always
    environment:
      POSTGRES_PASSWORD: $HASURA_POSTGRES_PASSWORD
      POSTGRES_USER: $HASURA_POSTGRES_USER

  hasura:
    image: hasura/graphql-engine:${HASURA_VERSION:-v2.39.0}
    restart: always
    depends_on:
      - hasura-postgres
    ports:
      - "8080:8080"
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://$HASURA_POSTGRES_USER:$HASURA_POSTGRES_PASSWORD@$HASURA_POSTGRES_HOST:5432/postgres
      PG_DATABASE_URL: postgres://$HASURA_POSTGRES_USER:$HASURA_POSTGRES_PASSWORD@$HASURA_POSTGRES_HOST:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
    labels:
      - "traefik.http.routers.graphql-engine.priority=10"
      - "traefik.http.routers.graphql-engine.rule=PathPrefix(`/v1`)"
      - "traefik.http.routers.graphql-engine.entrypoints=web"
      - "traefik.http.services.graphql-engine-service.loadbalancer.server.port=8080"

  hasura-cli:
    build:
      context: ./backend
      args:
        VERSION: ${HASURA_VERSION}
    restart: always
    network_mode: host
    entrypoint: hasura console --admin-secret $HASURA_GRAPHQL_ADMIN_SECRET --address 0.0.0.0 --console-hge-endpoint http://localhost:8080 --no-browser
    volumes:
      - ./backend/hasura:/src/hasura
    working_dir: /src/hasura
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET
      HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"

  traefik:
    image: traefik:${TRAEFIK_VERSION:-latest}
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--serversTransport.insecureSkipVerify=true"
    ports:
      - "80:80"
      - "8181:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  ngrok:
    image: ngrok/ngrok:alpine
    restart: always
    environment:
      NGROK_AUTHTOKEN: ${NGROK_TOKEN}
      DOMAIN_NAME: helped-amazing-snipe.ngrok-free.app
    command: http --domain=${DOMAIN_NAME} traefik:80
    depends_on:
      - traefik
    ports:
      - "4040:4040"

  fief-worker:
    image: ghcr.io/fief-dev/fief:${FIEF_VERSION:-latest}
    restart: always
    command: fief run-worker -p 1 -t 1
    env_file:
      - .env-feif
    depends_on:
      - fief-postgres
      - fief-redis

  fief-postgres:
    image: postgres:${FIEF_POSTGRES_VERSION:-latest}
    restart: always
    env_file:
      - .env-feif
    volumes:
      - fief-postgres-data:/var/lib/postgresql/data

  fief-redis:
    image: redis:alpine
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - fief-redis-data:/data

  fief-server:
    image: ghcr.io/fief-dev/fief:${FIEF_VERSION:-latest}
    restart: always
    command: fief run-server --ssl-keyfile /certs/selfsigned.key --ssl-certfile /certs/selfsigned.crt --proxy-headers --forwarded-allow-ips="*"
    env_file:
      - .env-feif
    depends_on:
      - fief-postgres
      - fief-redis
    volumes:
      - ./certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fief-server.rule=PathPrefix(`/login`)"
      - "traefik.http.routers.fief-server.entrypoints=web"
      - "traefik.http.services.fief-server.loadbalancer.server.scheme=https"
      - "traefik.http.services.fief-server.loadbalancer.server.port=443"
      - "traefik.http.middlewares.forward-https.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.fief-server.middlewares=forward-https"

  nuxt-frontend:
    build:
      context: ./frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt-frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.nuxt-frontend.loadbalancer.server.port=8100"
      - "traefik.http.routers.nuxt-frontend.priority=1"

volumes:
  fief-redis-data:
  fief-postgres-data:
