version: "3.6"
services:
  autoheal:
    image: willfarrell/autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    restart: always
  hasura-postgres:
    image: postgres:${HASURA_POSTGRES_VERSION:-16}
    restart: always
    environment:
      POSTGRES_PASSWORD: $HASURA_POSTGRES_PASSWORD
      POSTGRES_USER: $HASURA_POSTGRES_USER
  graphql-engine:
    image: hasura/graphql-engine:${HASURA_VERSION:-v2.39.0}
    ports:
      - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://$HASURA_POSTGRES_USER:$HASURA_POSTGRES_PASSWORD@$HASURA_POSTGRES_HOST:5432/postgres
      PG_DATABASE_URL: postgres://$HASURA_POSTGRES_USER:$HASURA_POSTGRES_PASSWORD@$HASURA_POSTGRES_HOST:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: $HASURA_GRAPHQL_ADMIN_SECRET
